version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.12.3
    steps:
    - checkout
    - run: go test ./...
  release:
    docker:
    - image: magneticio/kubist-util:v0.0.3
    steps:
    - checkout
    - add_ssh_keys
    - setup_remote_docker:
        docker_layer_caching: true
    - run: git config user.email "${GITHUB_EMAIL}"
    - run: git config user.name "${CIRCLE_PROJECT_USERNAME}"
    - run:
        name: "Update version tag"
        command: |
          wget https://github.com/magneticio/semver-shell/releases/download/v0.2.0/semver_version.sh
          chmod +x semver_version.sh
          mkdir -p ./artifacts
          ./semver_version.sh -l text -f "./artifacts/version.txt"
    - run:
        name: "Publish image to docker hub"
        command: |
          VERSION=$(cat ./artifacts/version.txt)
          rm ./artifacts/version.txt
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t magneticio/vampkubist-istio-adapter:$VERSION .
          docker push magneticio/vampkubist-istio-adapter:$VERSION
          docker tag magneticio/vampkubist-istio-adapter:$VERSION magneticio/vampkubist-istio-adapter:latest
          docker push magneticio/vampkubist-istio-adapter:latest
          docker tag magneticio/vampkubist-istio-adapter:$VERSION magneticio/vampkubist-istio-adapter-dev:$VERSION
          docker push magneticio/vampkubist-istio-adapter-dev:$VERSION
          docker tag magneticio/vampkubist-istio-adapter:$VERSION magneticio/vampkubist-istio-adapter-dev:latest
          docker push magneticio/vampkubist-istio-adapter-dev:latest
workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          tags:
            only: /^(v)\d+\.\d+\.\d+$/
    - release:
        requires:
        - build
        filters:
          branches:
            only: master
